[package]
name = "lighthouse-output-usb-dmx"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serialport.workspace = true
lighthouse-domain = { path = "../domain" }
lighthouse-output-api = { path = "../output-api" }

[lints]
workspace = true
