[package]
name = "lighthouse-desktop"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2"
serde.workspace = true
serde_json.workspace = true
uuid = { version = "1.24.0", features = ["v4"] }
base64 = "0.22.1"
lighthouse-commands = { path = "../../crates/commands" }
lighthouse-domain = { path = "../../crates/domain" }
lighthouse-effects = { path = "../../crates/effects" }
lighthouse-fixture-library = { path = "../../crates/fixture-library" }
lighthouse-fixture-model = { path = "../../crates/fixture-model" }
lighthouse-ipc = { path = "../../crates/ipc" }
lighthouse-persistence = { path = "../../crates/persistence" }
lighthouse-show-engine = { path = "../../crates/show-engine" }
lighthouse-output-usb-dmx = { path = "../../crates/output-usb-dmx" }

[lints]
workspace = true
